<?php View::content(); ?>
<?php echo Form::open('proyecto/create/', 'POST','') ?>
<div class="container">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Nuevo Proyecto</h3>
                    </div><!-- /.box-header -->
                    <!-- form start -->
                    <form role="form">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="proyecto_nombre">Nombre</label>
                                <?= Form::text('proyecto.nombre', "size=20 maxlength=50 required='required'
                                placeholder='Escriba el nombre del proyecto' class='form-control'") ?>
                            </div>
                            <div class="form-group">
                                <label for="proyecto_descripcion">Descripcion</label>
                                <?= Form::text('proyecto.descripcion', "size=20 maxlength=200 required='required'
                                placeholder='Escriba la descripción del proyecto' class='form-control'") ?>
                            </div>
                        </div><!-- /.box-body -->

                        <div class="box-footer">
                            <?= Form::submit('Crear',"title='Crear' class='btn btn-success'"); ?>
                            <?= Form::button('Regresar',"title='Regresar' onclick= \"location.href= '".PUBLIC_PATH
                                .'proyecto'."'\" class='btn btn-default'") ?>
                        </div>
                    </form>
                </div><!-- /.box -->

            </div><!--/.col (left) -->
            <!-- right column -->
        </div>   <!-- /.row -->
    </section><!-- /.content -->
</div>
<?php echo Form::close() ?>