<?php
if($bandera){
    echo "Sesion Guardada Exitosamente!";
}
else{
    echo "Ocurrio un error al tratar de guardar la Sesion";
}
?>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><strong>Listado de Sesiones de <?= $proyecto->nombre?></strong></h3><br>
        <!--        <a href="--><?//= PUBLIC_PATH . 'sesion/create/' ?><!--" title="Nuevo" class='btn btn-success'>Nuevo</a>-->
        <a href="<?php echo PUBLIC_PATH . 'proyecto/' ?>" title="Atras" class='btn btn-default'>Atras</a><br><br>

        <div class="row">
            <div class="col-md-6">
                <?= Form::text('sesion.descripcion', "size=20 maxlength=200 required='required' placeholder='¿En qué estás trabajando?' class='form-control'") ?>
            </div>
            <div class="col-md-3">
                <?= Form::button('Empezar',"title='Empezar' onclick = 'carga()' class='btn btn-info'") ?>
                <?= Form::button('Detenerse',"title='Detenerse' onclick = 'detenerse()' class='btn btn-danger'") ?>
                <?= Form::hidden('sesion.proyectos_id','',$proyecto->id) ?>
            </div>
            <div class="col-md-3">
                <?= Form::text('sesion.duracion', "size=20 maxlength=10 placeholder='0min 0sec' class='form-control'
                disabled='true'") ?>
                <!--                <span id="minutos">0</span>:<span id="segundos">0</span>-->
            </div>
        </div>

    </div><!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <?php foreach( $campos  as $titulo => $valor): ?>
                    <th><?= $titulo ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($sesiones as $model): ?>
                <tr>
                    <?php
                    foreach($campos as $Campos): ?>
                        <td><?php
                            echo $model->$Campos; ?></td>
                        <?php
                    endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
            </tr>
            </tfoot>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->
