<?php  View::content(); ?>
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><strong>Listado de Proyectos</strong></h3><br>
        <a href="<?= PUBLIC_PATH . 'proyecto/create/' ?>" title="Nuevo" class='btn btn-success'>Nuevo</a>
    </div><!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <?php foreach( $campos  as $titulo => $valor): ?>
                    <th><?= $titulo ?></th>
                    <?php endforeach; ?>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach($proyectos as $model): ?>
                    <tr>
                        <?php
                        foreach($campos as $Campos): ?>
                            <td><?php
                                echo $model->$Campos; ?></td>
                            <?php
                        endforeach; ?>
                        <td>
                            <a href="<?php echo PUBLIC_PATH . 'proyecto/edit/' . $model->id; ?>" title="Editar" class='btn btn-warning'>Editar</a>
                            <?php if(!Load::model('sesiones')->exists('proyectos_id='.$model->id))
                            { ?>
                                <a onclick="confirmar('<?php echo PUBLIC_PATH . 'proyecto/delete/' . $model->id; ?>')" title="Eliminar" class='btn btn-danger'>Eliminar</a>
                            <?php } ?>

                            <a href="<?php echo PUBLIC_PATH . 'proyecto/sesiones/' . $model->id; ?>" title="Ver Sesiones" class='btn btn-primary'>Ver Sesiones</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr>
                </tr>
            </tfoot>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->

<script>
/*$(document).ready(function(){
   $('#box-table-a').dataTable( { //CONVERTIMOS NUESTRO LISTADO DE LA FORMA DEL JQUERY.DATATABLES- PASAMOS EL ID DE LA TABLA
        "sPaginationType": "full_numbers" //DAMOS FORMATO A LA PAGINACION(NUMEROS)
    } );
})*/

//$(document).ready(function(){
//    alert('prueba');
//    $("#example1").DataTable();
//
//});

function confirmar(ruta)
{
    texto = '<center><img class="edit" title="Procesar Solicitud" src="<?php echo PUBLIC_PATH ?>img/prompt/delete.png" /><h1>¿Está seguro de realizar esta Acción?</h2></center>';
	$.prompt(
        texto, {
            buttons: { "Sí": true, "No":false},
            submit:function(e,v,m,f)
            {
                if(v)//si le dio al boton que el valor es TRUE, redirecciono
                    location.href=ruta; //redirecciono a la ruta enviada
            },
        }
    );
}

$(function () {
    $("#example1").DataTable();
});
</script>