<?php  View::content(); ?>
<div id="resultadoajax">
<div class="box">
    <div class="box-header">
        <h3 class="box-title"><strong>Listado de Sesiones de <?= $proyecto->nombre?></strong></h3><br>
<!--        <a href="--><?//= PUBLIC_PATH . 'sesion/create/' ?><!--" title="Nuevo" class='btn btn-success'>Nuevo</a>-->
        <a href="<?php echo PUBLIC_PATH . 'proyecto/' ?>" title="Atras" class='btn btn-default'>Atras</a><br><br>

        <div class="row">
            <div class="col-md-6">
                <?= Form::text('sesion.descripcion', "size=20 maxlength=200 required='required' placeholder='¿En qué estás trabajando?' class='form-control'") ?>
            </div>
            <div class="col-md-3">
                <?= Form::button('Empezar',"title='Empezar' onclick = 'carga()' class='btn btn-info'") ?>
                <?= Form::button('Detenerse',"title='Detenerse' onclick = 'detenerse()' class='btn btn-danger'") ?>
                <?= Form::hidden('sesion.proyectos_id','',$proyecto->id) ?>
            </div>
            <div class="col-md-3">
                <?= Form::text('sesion.duracion', "size=20 maxlength=10 placeholder='0min 0sec' class='form-control'
                disabled='true'") ?>
            </div>
        </div>

    </div><!-- /.box-header -->
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
                <?php foreach( $campos  as $titulo => $valor): ?>
                    <th><?= $titulo ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($sesiones as $model): ?>
                <tr>
                    <?php
                    foreach($campos as $Campos): ?>
                        <td><?php
                            echo $model->$Campos; ?></td>
                        <?php
                    endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
            </tr>
            </tfoot>
        </table>
    </div><!-- /.box-body -->
</div><!-- /.box -->
</div>

<script>
/*$(document).ready(function(){
   $('#box-table-a').dataTable( { //CONVERTIMOS NUESTRO LISTADO DE LA FORMA DEL JQUERY.DATATABLES- PASAMOS EL ID DE LA TABLA
        "sPaginationType": "full_numbers" //DAMOS FORMATO A LA PAGINACION(NUMEROS)
    } );
})*/
//window.onload = function() {
//    carga();
//};

function confirmar(ruta)
{
    texto = '<center><img class="edit" title="Procesar Solicitud" src="<?php echo PUBLIC_PATH ?>img/prompt/delete.png" /><h1>¿Está seguro de realizar esta Acción?</h2></center>';
	$.prompt(
        texto, {
            buttons: { "Sí": true, "No":false},
            submit:function(e,v,m,f)
            {
                if(v)//si le dio al boton que el valor es TRUE, redirecciono
                    location.href=ruta; //redirecciono a la ruta enviada
            },
        }
    );
}

//setInterval
var cronometro;

function detenerse()
{
    clearInterval(cronometro);
    descripcion = document.getElementById("sesion_descripcion").value;
    duracion = document.getElementById("sesion_duracion").value;
    proyectoid = document.getElementById("sesion_proyectos_id").value;
    contadorString.value='';
    $.ajax({
        type: "POST",
        url: "<?php echo PUBLIC_PATH ?>"+"proyecto/createsesion/"+descripcion+'/'+duracion+'/'+proyectoid,
        success: function(html)
        {
            $("#resultadoajax").html(html);
        }
    });
}

function carga()
{
    contador_s =0;
    contador_m =0;
    s = document.getElementById("segundos");
    m = document.getElementById("minutos");
    contadorString = document.getElementById("sesion_duracion");

    cronometro = setInterval(
        function(){
            if(contador_s==60)
            {
                contador_s=0;
                contador_m++;

                if(contador_m==60)
                {
                    contador_m=0;
                }
            }

            contador_s++;
            contadorString.value=contador_m+' min '+contador_s+' sg';
        }
        ,1000);
}

</script>