<?php  View::content(); ?>
<div id="resultadoajax">
<div class="panel panel-primary">
    <div class="panel-body" style="min-height: 600px; ">
        <?php $i = 4;
        $privez=true;?>
        <?php foreach($imagenes as $imagen): ?>

            <div class="col-2" style="padding: 30px"><img class="img-rounded" src="<?php echo str_replace('/public/','',$imagen->direc_fisica); ?>" style="width:100%;height: 130px" ></div>

        <?php endforeach; ?>
    </div>
</div>
<script>
    function subirimagen(obj){
        nombre = obj.value;
        $.ajax({
            type: "POST",
            url: "<?php echo PUBLIC_PATH ?>"+"gestorimagen/create/"+nombre,
            success: function(html)
            {
                $("#resultadoajax").html(html);
            }
        });
    }
</script>
