<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>prueba</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

      <!-- jQuery 2.1.3 -->
      <?php echo Tag::js('adminLTE/plugins/jquery/jQuery-2.1.3.min'); ?>

      <!-- Bootstrap 3.3.2 JS -->
      <?php echo Tag::js('adminLTE/bootstrap/bootstrap.min'); ?>

      <!-- FastClick -->
      <?php echo Tag::js('adminLTE/plugins/fastclick/fastclick.min'); ?>

      <!-- AdminLTE App -->
      <?php echo Tag::js('adminLTE/theme_style/js/app.min'); ?>

      <!-- Sparkline -->
      <?php echo Tag::js('adminLTE/plugins/sparkline/jquery.sparkline.min'); ?>

      <!-- jvectormap -->
      <?php echo Tag::js('adminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min'); ?>
      <?php echo Tag::js('adminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en'); ?>

      <!-- daterangepicker -->
      <?php echo Tag::js('adminLTE/plugins/daterangepicker/daterangepicker'); ?>

      <!-- datepicker -->
      <?php echo Tag::js('adminLTE/plugins/datepicker/bootstrap-datepicker'); ?>

      <!-- iCheck -->
      <?php echo Tag::js('adminLTE/plugins/iCheck/icheck.min'); ?>

      <!-- SlimScroll 1.3.0 -->
      <?php echo Tag::js('adminLTE/plugins/slimScroll/jquery.slimscroll.min'); ?>

      <!-- ChartJS 1.0.1 -->
      <?php echo Tag::js('adminLTE/plugins/chartjs/Chart.min'); ?>

      <!-- DataTables -->
      <?php echo Tag::js('adminLTE/plugins/datatables/jquery.dataTables.min'); ?>

      <?php echo Tag::js('adminLTE/plugins/datatables/dataTables.bootstrap.min'); ?>


    <!-- Bootstrap 3.3.2 -->
    <?php Tag::css('AdminLTE/bootstrap/css/bootstrap.min'); ?>

    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />

    <!-- Morris chart -->
    <?php Tag::css('AdminLTE/morris/morris'); ?>

    <!-- jvectormap -->
    <?php Tag::css('AdminLTE/jvectormap/jquery-jvectormap-1.2.2'); ?>

    <!-- Daterange picker -->
    <?php Tag::css('AdminLTE/daterangepicker/daterangepicker-bs3'); ?>

    <!-- Theme style -->
    <?php Tag::css('AdminLTE/theme_style/AdminLTE.min'); ?>

    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <?php Tag::css('AdminLTE/theme_style/skins/skin-blue.min'); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->

    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- Print all css -->
    <?php echo Html::includecss();?>

  </head>

  <body class="skin-blue">

    <div class="wrapper">

<?php View::partial('adminLTE/navbar'); ?>

<?php View::partial('adminLTE/sidebar'); ?>

<div class="content-wrapper">

<?php View::content(); ?>

</div>

<?php View::partial('adminLTE/footer'); ?>

    </div>

  </body>

</html>